[2024-09-19T17:33:19.433+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_python_operator_v06.greet manual__2024-09-19T17:33:18.130860+00:00 [queued]>
[2024-09-19T17:33:19.437+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_python_operator_v06.greet manual__2024-09-19T17:33:18.130860+00:00 [queued]>
[2024-09-19T17:33:19.437+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-09-19T17:33:19.437+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2024-09-19T17:33:19.437+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-09-19T17:33:19.442+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): greet> on 2024-09-19 17:33:18.130860+00:00
[2024-09-19T17:33:19.444+0000] {standard_task_runner.py:52} INFO - Started process 7717 to run task
[2024-09-19T17:33:19.445+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_operator_v06', 'greet', 'manual__2024-09-19T17:33:18.130860+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp6azhm8tg', '--error-file', '/tmp/tmpuyh6hpvi']
[2024-09-19T17:33:19.446+0000] {standard_task_runner.py:80} INFO - Job 47: Subtask greet
[2024-09-19T17:33:19.470+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_python_operator_v06.greet manual__2024-09-19T17:33:18.130860+00:00 [running]> on host a83b02c526f7
[2024-09-19T17:33:19.561+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=faruk3d
AIRFLOW_CTX_DAG_ID=dag_with_python_operator_v06
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2024-09-19T17:33:18.130860+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-19T17:33:18.130860+00:00
[2024-09-19T17:33:19.561+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 1 required positional argument: 'age'
[2024-09-19T17:33:19.565+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_operator_v06, task_id=greet, execution_date=20240919T173318, start_date=20240919T173319, end_date=20240919T173319
[2024-09-19T17:33:19.569+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 47 for task greet (greet() missing 1 required positional argument: 'age'; 7717)
[2024-09-19T17:33:19.584+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-19T17:33:19.596+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
