[2024-09-19T17:32:06.882+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_python_operator_v06.greet manual__2024-09-19T17:32:04.913932+00:00 [queued]>
[2024-09-19T17:32:06.886+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_python_operator_v06.greet manual__2024-09-19T17:32:04.913932+00:00 [queued]>
[2024-09-19T17:32:06.886+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-09-19T17:32:06.887+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2024-09-19T17:32:06.887+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-09-19T17:32:06.892+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): greet> on 2024-09-19 17:32:04.913932+00:00
[2024-09-19T17:32:06.894+0000] {standard_task_runner.py:52} INFO - Started process 7616 to run task
[2024-09-19T17:32:06.895+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_operator_v06', 'greet', 'manual__2024-09-19T17:32:04.913932+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp3tsjk4h0', '--error-file', '/tmp/tmp8oxyilrf']
[2024-09-19T17:32:06.896+0000] {standard_task_runner.py:80} INFO - Job 43: Subtask greet
[2024-09-19T17:32:06.920+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_python_operator_v06.greet manual__2024-09-19T17:32:04.913932+00:00 [running]> on host a83b02c526f7
[2024-09-19T17:32:07.013+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=faruk3d
AIRFLOW_CTX_DAG_ID=dag_with_python_operator_v06
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2024-09-19T17:32:04.913932+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-19T17:32:04.913932+00:00
[2024-09-19T17:32:07.013+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 1 required positional argument: 'age'
[2024-09-19T17:32:07.017+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_operator_v06, task_id=greet, execution_date=20240919T173204, start_date=20240919T173206, end_date=20240919T173207
[2024-09-19T17:32:07.021+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 43 for task greet (greet() missing 1 required positional argument: 'age'; 7616)
[2024-09-19T17:32:07.041+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-19T17:32:07.053+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
