[2024-09-19T17:15:40.217+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_python_operator_v04.greet scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-09-19T17:15:40.221+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_python_operator_v04.greet scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-09-19T17:15:40.221+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-09-19T17:15:40.221+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2024-09-19T17:15:40.221+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-09-19T17:15:40.226+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): greet> on 2024-09-18 00:00:00+00:00
[2024-09-19T17:15:40.228+0000] {standard_task_runner.py:52} INFO - Started process 6383 to run task
[2024-09-19T17:15:40.229+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_operator_v04', 'greet', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpf8i58gro', '--error-file', '/tmp/tmpnma6z2x2']
[2024-09-19T17:15:40.230+0000] {standard_task_runner.py:80} INFO - Job 18: Subtask greet
[2024-09-19T17:15:40.255+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_python_operator_v04.greet scheduled__2024-09-18T00:00:00+00:00 [running]> on host a83b02c526f7
[2024-09-19T17:15:40.284+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=faruk3d
AIRFLOW_CTX_DAG_ID=dag_with_python_operator_v04
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2024-09-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-18T00:00:00+00:00
[2024-09-19T17:15:40.284+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 16, in greet
    name = ti.xcoms_pull(task_id = "get_name")
AttributeError: 'TaskInstance' object has no attribute 'xcoms_pull'
[2024-09-19T17:15:40.365+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_operator_v04, task_id=greet, execution_date=20240918T000000, start_date=20240919T171540, end_date=20240919T171540
[2024-09-19T17:15:40.371+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 18 for task greet ('TaskInstance' object has no attribute 'xcoms_pull'; 6383)
[2024-09-19T17:15:40.414+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-19T17:15:40.429+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
